name: Deploy Angular App

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    name: Deploy Demo
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '^20.9.0'

    - name: Install Dependencies
      run: npm ci

    - name: Build Angular Project
      run: npm run build --base-href demo

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/demo/browser