name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-demo:
    name: Deploy Demo
    run: |
      cd demo
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url}}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '^20.9.0'

    - name: Install Dependencies
      run: npm ci

    - name: Build Demo
      run: npm run build

    - name: Debug Build Output
      run: ls -la dist/demo

    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/demo

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4